[package]
name = "tendermint-recursion-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
sp1-zkvm.workspace = true
sp1-verifier.workspace = true
borsh.workspace = true
tendermint-recursion-types.workspace = true
tendermint-program-types.workspace = true
